### ISSUE TITLE
Question about utility balance ratio

### ISSUE THREAD

**Issue by stellamulia** [ighdez/choicedesign#1]
Hi Ignacio,

I have a question about the utility balance ratio (`ubalance_ratio`) output. 

In this [.ipynb file](https://drive.google.com/file/d/1DFxTMGnD1q9LSYfaJHhZl7AmKB1ULwHj/view?usp=sharing), the utility balance ratio is 67.3%. However, I calculated the utility balance ratio in Ngene in [utilitybalancecalculation.ngd](https://drive.google.com/file/d/1MUqor8QY9RWt7BGgb-hb_66fsDlEq4U2/view?usp=sharing) (or see this [excel file](https://docs.google.com/spreadsheets/d/1XPNVhU1g0EwlV11w8cDRMm3jKSO_kSRC/edit?usp=share_link&ouid=112699531882523470693&rtpof=true&sd=true) if an Ngene file is a hassle), and the result is 82.72%. The excel file also contains my manual calculation which results in the same number (82.72%). 

Is this perhaps a bug, or did I interpret/use something incorrectly?

Thanks in advance!

**Comment by ighdez** [comment]
Hi @stellamulia, thanks for noticing this issue. I will come with this in due time.

**Comment by ighdez** [comment]
Hi @stellamulia ,

Indeed, the utility balance computation was taking the initial design matrix instead the final design (line 182 of `design.py`). It is very likely that this bug was generating while I was restructuring the code for releasing ChoiceDesign. Now it is corrected.

In addition, this report made me realise that a method to evaluate designs ex-post is a useful adding. Thus, `RUMDesign` now incorporates the method `evaluate`, which takes a pandas dataframe as an input (which we assume it is a design generated by ChoiceDesign or with an equivalent specification) and delivers the D-error and utility balance. To evaluate the design, `evaluate()` takes the arguments you defined to initialise the `RUMDesign` object (i.e., attributes, priors, etc).

Let me know if you have further questions about this. I modified the example notebooks to incorporate the evaluation of the design as well :)

Thank you very much for spotting this bug!!

**Comment by stellamulia** [comment]
Awesome, thank you @ighdez !!
